# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Cláudia Kênia da Silva
# Description of the Site
description: Analista de Dados | Power BI, Python, R e SQL
# URL of Image of the Site
site-image:
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Dashboard (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/meta.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: clauke14@gmail.com
# facebook_username: thedevslot
# twitter_username: thedevslot
# instagram_username: thedevslot
linkedin_username: claudia-kenia
github_username: clauke
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Cláudia Kênia
# URL for the Image of the Author
author-image: /assets/images/Foto_Git.png
# 63 Palavras Sobre o Autor
author-about: Profissional de TI com mais de 25 anos de experiência, atuando nos últimos anos com foco em Análise de Dados, Business Intelligence e Analytics. Possuo experiência prática em projetos de dados end-to-end, envolvendo coleta, tratamento e modelagem dos dados (ETL), análise exploratória e estatística, além da construção de dashboards e visualizações para apoio à tomada de decisão. Trabalho com ferramentas como Python, R, SQL e Power BI, sempre buscando transformar dados em informação clara, confiável e acionável para o negócio.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/clauke

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
